### ISSUE TITLE
RT extension

### ISSUE THREAD

**Issue by vesaalexandru95** [Slicer/SlicerDocker#52] opened 2022-08-19 16:27 UTC
Hello !
I’m running the docker version of 3D-slicer : [GitHub - Slicer/SlicerDocker: Build, package, test, and run 3D Slicer and Slicer Extensions in Docker.](https://github.com/Slicer/SlicerDocker)

I have a problem when i’m trying to export the RT contour . I have also installed all the plugins.

"Failed to export using plugin DicomRtImportExportPluginClass
Traceback (most recent call last):
File “”, line 3, in
File “/home/sliceruser/Slicer/NA-MIC/Extensions-30822/SlicerRT/lib/Slicer-5.0/qt-scripted-modules/DicomRtImportExportPlugin.py”, line 126, in export
message = slicer.modules.dicomrtimportexport.logic().ExportDicomRTStudy(exportablesCollection)
AttributeError: module ‘modules’ has no attribute ‘dicomrtimportexport’ "

How should I approach this ?
Thanks,
Alex

**Comment by vesaalexandru95** [comment] 2022-08-29 07:51
Hello ! 
Does anyone know about this problem?
Thanks,
Alex

**Comment by cpinter** [comment] 2022-09-05 11:02
Duplicate of forum thread https://discourse.slicer.org/t/rt-slicer-plugin/24836

I'm closing this issue and we can continue discussing on Discourse. If there is anything to change in the source codes we can add an issue in the appropriate repository, which probably will not be SlicerDocker.

**Closed by cpinter** 2022-09-05 11:02 UTC
Labels: question
